options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/vodaf24dus-443/newsletter-ai-image:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/vodaf24dus-443/newsletter-ai-image:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "newsletter-ai"
      - "--image"
      - "gcr.io/vodaf24dus-443/newsletter-ai-image:$COMMIT_SHA"
      - "--region"
      - "us-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "4Gi"
images:
  - "gcr.io/vodaf24dus-443/newsletter-ai-image:$COMMIT_SHA"
