import streamlit as st

config = {'scrollZoom': True, 'displayModeBar': True, 'displaylogo': False}
st.set_page_config(page_title="NewsLetter.AI", page_icon=":chat-plus-outline:", layout="wide", initial_sidebar_state="expanded", menu_items=None)

st.write("""
## Newsletter.AI

Employees in our company struggle with information overload from the numerous weekly newsletters generated by various departments.

It is difficult for employees to read all of them, or to easily search through past newsletters.

Using Generative Artificial Intelligence, Newsletter.AI processes newsletter content, allowing you to ask questions and receive relevant answers.

Simply type your question, and Newsletter.AI compiles an accurate response by retrieving information from past and present newsletters.

#### Navigation

Click on the sidebar to interact with Newsletter.AI chatbot. \n

#### Technology

Newsletter.AI uses three key technologies:

1. Retrieval-Augmented Generation (RAG)
2. Large Language Models (LLMs)
3. Google Cloud  (Cloud Run and Vertex AI)

For detailed technology deep-dive, check out the [github repo](https://github.com/kanad13/NewsLetter-AI).
				 """)
